// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOo43ktjxApnppvs82FNQ3HQm1V5PTvc',
    appId: '1:574044180622:web:cfbf22af6e4ad1b1dab9df',
    messagingSenderId: '574044180622',
    projectId: 'multiplatformappuwg',
    authDomain: 'multiplatformappuwg.firebaseapp.com',
    databaseURL: 'https://multiplatformappuwg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'multiplatformappuwg.firebasestorage.app',
    measurementId: 'G-V9T4TXKKGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7syr7tc4tCKignu5AwWq6otYBLKnEbuE',
    appId: '1:574044180622:android:d59dc461e2459961dab9df',
    messagingSenderId: '574044180622',
    projectId: 'multiplatformappuwg',
    databaseURL: 'https://multiplatformappuwg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'multiplatformappuwg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwWG2yToAatluqi8kFCuJSF9cvrUGQvs4',
    appId: '1:574044180622:ios:416baf2007e7b4a9dab9df',
    messagingSenderId: '574044180622',
    projectId: 'multiplatformappuwg',
    databaseURL: 'https://multiplatformappuwg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'multiplatformappuwg.firebasestorage.app',
    iosClientId: '574044180622-t4ijmdvf8vtdqn4uhk6l4800m9eqjfa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aaa1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwWG2yToAatluqi8kFCuJSF9cvrUGQvs4',
    appId: '1:574044180622:ios:416baf2007e7b4a9dab9df',
    messagingSenderId: '574044180622',
    projectId: 'multiplatformappuwg',
    databaseURL: 'https://multiplatformappuwg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'multiplatformappuwg.firebasestorage.app',
    iosClientId: '574044180622-t4ijmdvf8vtdqn4uhk6l4800m9eqjfa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aaa1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUOo43ktjxApnppvs82FNQ3HQm1V5PTvc',
    appId: '1:574044180622:web:4a28e6fdabdf3783dab9df',
    messagingSenderId: '574044180622',
    projectId: 'multiplatformappuwg',
    authDomain: 'multiplatformappuwg.firebaseapp.com',
    databaseURL: 'https://multiplatformappuwg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'multiplatformappuwg.firebasestorage.app',
    measurementId: 'G-H7EKC3LQYP',
  );
}
